before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.Version={{ .Tag }}"
    main: ./cmd/words/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
#    hooks:
#      post:
#        - upx "{{ .Path }}"
archives:
  - id: words
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
# https://goreleaser.com/customization/homebrew/
brews:
  - name: words
    tap:
      owner: LinkinStars
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/LinkinStars/words"
    description: "极客就要用终端来背单词"
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: LinkinStars
    name: words
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^assets:'
