before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X "main.Version={{ .Tag }}"
    main: ./cmd/words/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
#    hooks:
#      post:
#        - upx "{{ .Path }}"
archives:
  - id: words
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: LinkinStars
    name: words
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^assets:'
